### ISSUE TITLE
Is L1 adaptive controller able to compensate for the unmatched uncertainties?

### ISSUE THREAD

**Issue by WangJintao1998** [stevemessinger/L1_MPC-HELI#2]
In simulation, I gave the quadrotor a desired pose and generated 4m/s wind disturbances along the y axis. Even though I added the L1 augmentation, there was still a huge error in y position. I wonder if it's my problem or the L1 adaptive controller simply couldn't reject disturbances along x and y axes?

**Comment by MatthewFehl365** [comment]
The simulation and whole project in general is still under heavy development so many things aren't working correctly. We will update the ReadMe when a fully functional release is done to reflect the fixes.
